version: '2'
services:
  mongo:
    image: mongo
    ports:
    - '27017:27017'
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_user
      MONGO_INITDB_ROOT_PASSWORD: Wzj_mysql01
    volumes:
    - '/opt/data/mongodb:/data/db'
