server:
  port: ${server_port:5806}

spring:
  application:
    name: cinema-server
#  profiles:
#    include: mongodb


video:
  type:
    movie: 1
    tv: 2
    show: 3
    cartoon: 4

# Set log level
logging:
  level:
    root: INFO
    org.springframework.data.mongodb: WARN