server:
  port: ${server_port:5806}

spring:
  application:
    name: cinema-server
#  profiles:
#    include: mongodb


# Set log level
logging:
  level:
    root: INFO
    org.springframework.data.mongodb: WARN